<!DOCTYPE html/>
<html lang="{{Config::get('app.locale')}}" @if(Config::get('app.locale') == 'ar') dir="rtl" @endif >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
    <link rel="shortcut icon" href="{{ asset('images/logo.svg') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <style>
        .column {
            margin: 15px 15px 0;
            padding: 0;
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            grid-template-rows: repeat(3, 5vw);
            column-gap: 15px;
        }

        .column div {
            width: 300px;
            height: 200px;
            margin: 0 0 0 25px;
            padding: 0;
        }


        @media  screen and (max-width: 600px) {
            .column {
                display: flex;
                flex-direction: column;
                flex-wrap: wrap;
            }
        }
        .scale-up-center {
            -webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
            animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
        }
        /* ----------------------------------------------
 * Generated by Animista on 2022-5-24 11:56:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

        /**
         * ----------------------------------------
         * animation scale-up-center
         * ----------------------------------------
         */
        @-webkit-keyframes scale-up-center {
            0% {
                -webkit-transform: scale(0.5);
                transform: scale(0.5);
            }
            100% {
                -webkit-transform: scale(1);
                transform: scale(1);
            }
        }
        @keyframes scale-up-center {
            0% {
                -webkit-transform: scale(0.5);
                transform: scale(0.5);
            }
            100% {
                -webkit-transform: scale(1);
                transform: scale(1);
            }
        }

    </style>
</head>
<body class="public">
    <div class="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{ route('public.home')}}">
                <img src="{{asset('images/logo.svg')}}" height="50" alt="logo">
            </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav px-0 mx-auto mb-2 mb-lg-0">
                  {{-- <li class="nav-item">
                    <a class="nav-link" href="{{ route('public.informations-bank')}}">بنك المعلومات</a>
                  </li> --}}
                  <li class="nav-item">
                    <a class="nav-link" href="{{ route('public.about')}}">من نحن</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ route('public.contact-p')}}">تواصل معنا</a>
                  </li>
                </ul>
                  <a class="btn btn-dark" href="{{ route("public.login-p") }}">تسجيل الدخول</a>
              </div>
            </div>
          </nav>
    </div>
        @yield('content')



    <footer style="padding: 10px">
        <p><small>جمعية امل هي جمعية غير ربحية تعمل على تمكين وتعزيز قدرات النساء في وضعية صعبة لعيش حياة كريمة, مستقلة وولوج سوق الشغل</small> <b>جميع الحقوق محفوظة حقوق التأليف والنشر.
                المنتج
                مخصص
                لجمعية أمل</b>  &copy;	</p>
    </footer>
    <script src="{{ asset('js/app.js') }}"></script>
   <script>
       $(".pic").hover( function (e) {
           if ($(this).hasClass("scale-up-center")){
               $(this).removeClass("scale-up-center")
           }
           $(this).addClass("scale-up-center")
       })
   </script>
</body>
</html>
